[package]
name = "moc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "client"
path = "client/src/main.rs"

[[bin]]
name = "cache"
path = "src/main.rs"

[dependencies]
log = "0.4.20"
